a=input('Digite qualquer coisa:')
print(type(a))
print('É alfanumero?', a.isalnum())
print('É uma letra?', a.isalpha())
print('É um numero decimal?', a.isdecimal())
print('É um digito?', a.isdigit())
print('É um identificador?', a.isidentifier())
print('As letras estão minusculas?', a.islower())
print('É um numero', a.isnumeric())
print('É um imprimivel', a.isprintable())
print('É um espaço?', a.isspace())
print('É um titulo?', a.istitle())
print('As letras estão maiusculas?', a.isupper())
